// src/components/3d/FloatingOrb.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRenderLoop } from "@tresjs/core";
import * as THREE from "three";

const props = withDefaults(
  defineProps<{
    color: string;
    speed?: number;
    scale?: number;
  }>(),
  { speed: 1, scale: 1 }
);

const meshRef = ref<THREE.Mesh | null>(null);

const { onLoop } = useRenderLoop();
onLoop(({ elapsed }) => {
  if (!meshRef.value) return;
  const t = elapsed * props.speed;
  meshRef.value.position.y = Math.sin(t) * 0.3;
  meshRef.value.rotation.x = Math.sin(t * 0.5) * 0.2;
  meshRef.value.rotation.y = Math.cos(t * 0.3) * 0.2;
});
</script>

<template>
  <TresMesh ref="meshRef" :position="[0, 0, 0]">
    <TresSphereGeometry :args="[props.scale, 32, 32]" />
    <TresMeshStandardMaterial
      :color="color"
      :transparent="true"
      :opacity="0.6"
      :roughness="0.2"
      :metalness="0.8"
      :emissive="color"
      :emissive-intensity="0.3"
    />
  </TresMesh>
</template>

// src/components/3d/FloatingOrb.tsx
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { Sphere } from "@react-three/drei";
import * as THREE from "three";

interface FloatingOrbProps {
  color: string;
  speed?: number;
  scale?: number;
}

export default function FloatingOrb({ color, speed = 1, scale = 1 }: FloatingOrbProps) {
  const meshRef = useRef<THREE.Mesh>(null);

  useFrame((state) => {
    if (!meshRef.current) return;
    const t = state.clock.getElapsedTime() * speed;
    meshRef.current.position.y = Math.sin(t) * 0.3;
    meshRef.current.rotation.x = Math.sin(t * 0.5) * 0.2;
    meshRef.current.rotation.y = Math.cos(t * 0.3) * 0.2;
  });

  return (
    <Sphere ref={meshRef} args={[1 * scale, 32, 32]} position={[0, 0, 0]}>
      <meshStandardMaterial
        color={color}
        transparent
        opacity={0.6}
        roughness={0.2}
        metalness={0.8}
        emissive={color}
        emissiveIntensity={0.3}
      />
    </Sphere>
  );
}
