// src/pages/Register.tsx
import { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { toast } from "sonner";
import { UserPlus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { Session } from "@supabase/supabase-js";
import PaymentSetup from "@/components/PaymentSetup";

const registerSchema = z.object({
  firstName: z.string().trim().min(1, { message: "First name is required" }).max(50, { message: "First name must be less than 50 characters" }),
  lastName: z.string().trim().min(1, { message: "Last name is required" }).max(50, { message: "Last name must be less than 50 characters" }),
  phone: z.string().trim().regex(/^\+?[1-9]\d{1,14}$/, { message: "Please enter a valid phone number (e.g., +31636345484)" }),
  email: z.string().trim().email({ message: "Please enter a valid email address" }),
  password: z.string().min(6, { message: "Password must be at least 6 characters" }),
});

type RegisterFormData = z.infer<typeof registerSchema>;

const Register = () => {
  const [session, setSession] = useState<Session | null>(null);
  const [showPaymentStep, setShowPaymentStep] = useState(false);
  const navigate = useNavigate();

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<RegisterFormData>({
    resolver: zodResolver(registerSchema),
  });

  useEffect(() => {
    // Set up auth state listener
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      (event, session) => {
        setSession(session);
        // Only redirect if not on payment step
        if (session && !showPaymentStep) {
          navigate("/");
        }
      }
    );

    // Check for existing session
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
      if (session && !showPaymentStep) {
        navigate("/");
      }
    });

    return () => subscription.unsubscribe();
  }, [navigate, showPaymentStep]);

  const onSubmit = async (data: RegisterFormData) => {
    try {
      const redirectUrl = `${window.location.origin}/`;
      
      const { error } = await supabase.auth.signUp({
        email: data.email,
        password: data.password,
        options: {
          emailRedirectTo: redirectUrl,
          data: {
            first_name: data.firstName,
            last_name: data.lastName,
            phone: data.phone,
          },
        },
      });

      if (error) {
        if (error.message.includes("already registered")) {
          toast.error("Account exists", {
            description: "This email is already registered. Please login instead.",
          });
        } else {
          toast.error("Signup failed", {
            description: error.message,
          });
        }
        return;
      }

      toast.success("Account created!", {
        description: "Now let's set up your payment method for the trial.",
      });
      
      // Show payment setup step
      setShowPaymentStep(true);
    } catch (error) {
      console.error("Authentication error:", error);
      toast.error("Something went wrong", {
        description: "Please try again later.",
      });
    }
  };

  const handlePaymentComplete = () => {
    toast.success("Payment method added!", {
      description: "Your free trial has started. Enjoy!",
    });
    navigate("/dashboard");
  };

  const handleSkipPayment = () => {
    navigate("/dashboard");
  };

  return (
    <main className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20 flex items-center justify-center p-4 relative overflow-hidden">
      {/* Decorative background elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 right-0 w-96 h-96 bg-primary/5 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '8s' }} />
        <div className="absolute bottom-0 left-0 w-96 h-96 bg-accent/5 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '10s', animationDelay: '1s' }} />
      </div>

      {showPaymentStep ? (
        <PaymentSetup onComplete={handlePaymentComplete} onSkip={handleSkipPayment} />
      ) : (
        <Card className="w-full max-w-md shadow-[var(--shadow-soft)] border-border/50 bg-card/50 backdrop-blur-sm transition-all duration-500 hover:shadow-xl relative z-10">
        <CardHeader className="space-y-2 text-center">
          <div className="mx-auto w-12 h-12 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center mb-2 animate-in fade-in-0 zoom-in-50 duration-500">
            <UserPlus className="w-6 h-6 text-primary-foreground" />
          </div>
          <CardTitle className="text-3xl font-bold bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent animate-in fade-in-0 slide-in-from-bottom-4 duration-700">
            Create Account
          </CardTitle>
          <CardDescription className="text-base animate-in fade-in-0 slide-in-from-bottom-4 duration-700 delay-100">
            Sign up to get started
          </CardDescription>
        </CardHeader>

        <CardContent className="animate-in fade-in-0 slide-in-from-bottom-4 duration-700 delay-200">
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="firstName" className="text-sm font-medium">
                  First Name
                </Label>
                <Input
                  id="firstName"
                  type="text"
                  placeholder="John"
                  {...register("firstName")}
                  className="transition-all duration-300 focus:ring-2 focus:ring-primary/20"
                  disabled={isSubmitting}
                />
                {errors.firstName && (
                  <p className="text-sm text-destructive animate-in fade-in-0 slide-in-from-top-1 duration-300">
                    {errors.firstName.message}
                  </p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="lastName" className="text-sm font-medium">
                  Last Name
                </Label>
                <Input
                  id="lastName"
                  type="text"
                  placeholder="Doe"
                  {...register("lastName")}
                  className="transition-all duration-300 focus:ring-2 focus:ring-primary/20"
                  disabled={isSubmitting}
                />
                {errors.lastName && (
                  <p className="text-sm text-destructive animate-in fade-in-0 slide-in-from-top-1 duration-300">
                    {errors.lastName.message}
                  </p>
                )}
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="phone" className="text-sm font-medium">
                Phone Number
              </Label>
              <Input
                id="phone"
                type="tel"
                placeholder="+31636345484"
                {...register("phone")}
                className="transition-all duration-300 focus:ring-2 focus:ring-primary/20"
                disabled={isSubmitting}
              />
              {errors.phone && (
                <p className="text-sm text-destructive animate-in fade-in-0 slide-in-from-top-1 duration-300">
                  {errors.phone.message}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="email" className="text-sm font-medium">
                Email
              </Label>
              <Input
                id="email"
                type="email"
                placeholder="your@email.com"
                {...register("email")}
                className="transition-all duration-300 focus:ring-2 focus:ring-primary/20"
                disabled={isSubmitting}
              />
              {errors.email && (
                <p className="text-sm text-destructive animate-in fade-in-0 slide-in-from-top-1 duration-300">
                  {errors.email.message}
                </p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="password" className="text-sm font-medium">
                Password
              </Label>
              <Input
                id="password"
                type="password"
                placeholder="••••••••"
                {...register("password")}
                className="transition-all duration-300 focus:ring-2 focus:ring-primary/20"
                disabled={isSubmitting}
              />
              {errors.password && (
                <p className="text-sm text-destructive animate-in fade-in-0 slide-in-from-top-1 duration-300">
                  {errors.password.message}
                </p>
              )}
            </div>

            <Button
              type="submit"
              className="w-full bg-gradient-to-r from-primary to-accent hover:opacity-90 transition-all duration-300 shadow-md hover:shadow-lg font-medium"
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <span className="flex items-center gap-2">
                  <div className="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
                  Creating account...
                </span>
              ) : (
                <span>Sign Up</span>
              )}
            </Button>
          </form>

          <div className="mt-6 text-center">
            <p className="text-sm text-muted-foreground">
              Already have an account?{" "}
              <Link to="/login" className="text-primary font-medium hover:underline">
                Sign in
              </Link>
            </p>
          </div>
        </CardContent>
      </Card>
      )}
    </main>
  );
};

export default Register;

// src/views/Register.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { useRouter, RouterLink } from "vue-router";
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import Button from "@/components/ui/button.vue";
import Input from "@/components/ui/input.vue";
import Label from "@/components/ui/label.vue";
import PaymentSetup from "@/components/PaymentSetup.vue";
import { toast } from "vue-sonner";
import { UserPlus } from "lucide-vue-next";
import { supabase } from "@/integrations/supabase/client";

const router = useRouter();
const showPaymentStep = ref(false);

const schema = toTypedSchema(
  z.object({
    firstName: z.string().trim().min(1, { message: "First name is required" }).max(50),
    lastName: z.string().trim().min(1, { message: "Last name is required" }).max(50),
    phone: z.string().trim().regex(/^\+?[1-9]\d{1,14}$/, { message: "Please enter a valid phone number (e.g., +31636345484)" }),
    email: z.string().trim().email({ message: "Please enter a valid email address" }),
    password: z.string().min(6, { message: "Password must be at least 6 characters" }),
  })
);

const { handleSubmit, defineField, errors, isSubmitting } = useForm({ validationSchema: schema });
const [firstName, firstNameAttrs] = defineField("firstName");
const [lastName, lastNameAttrs] = defineField("lastName");
const [phone, phoneAttrs] = defineField("phone");
const [email, emailAttrs] = defineField("email");
const [password, passwordAttrs] = defineField("password");

let authSubscription: { unsubscribe: () => void } | null = null;

onMounted(() => {
  const { data } = supabase.auth.onAuthStateChange((event, session) => {
    if (event === "SIGNED_IN" && session && !showPaymentStep.value) router.push("/dashboard");
  });
  authSubscription = data.subscription;

  supabase.auth.getSession().then(async ({ data: { session } }) => {
    if (session && !showPaymentStep.value) {
      const { data: { user }, error } = await supabase.auth.getUser();
      if (user && !error) {
        router.push("/dashboard");
      } else {
        await supabase.auth.signOut();
      }
    }
  });
});

onUnmounted(() => authSubscription?.unsubscribe());

const onSubmit = handleSubmit(async (values) => {
  const { error } = await supabase.auth.signUp({
    email: values.email,
    password: values.password,
    options: {
      emailRedirectTo: `${window.location.origin}/`,
      data: {
        first_name: values.firstName,
        last_name: values.lastName,
        phone: values.phone,
      },
    },
  });

  if (error) {
    if (error.message.includes("already registered")) {
      toast.error("Account exists", { description: "This email is already registered. Please login instead." });
    } else {
      toast.error("Signup failed", { description: error.message });
    }
    return;
  }

  toast.success("Account created!", { description: "Now let's set up your payment method for the trial." });
  showPaymentStep.value = true;
});

const handlePaymentComplete = () => {
  toast.success("Payment method added!", { description: "Your free trial has started. Enjoy!" });
  router.push("/dashboard");
};

const handleSkipPayment = () => router.push("/dashboard");
</script>

<template>
  <main class="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20 flex items-center justify-center p-4 relative overflow-hidden">
    <div class="absolute inset-0 overflow-hidden pointer-events-none">
      <div class="absolute top-0 right-0 w-96 h-96 bg-primary/5 rounded-full blur-3xl animate-pulse" style="animation-duration: 8s" />
      <div class="absolute bottom-0 left-0 w-96 h-96 bg-accent/5 rounded-full blur-3xl animate-pulse" style="animation-duration: 10s; animation-delay: 1s" />
    </div>

    <PaymentSetup v-if="showPaymentStep" :on-complete="handlePaymentComplete" :on-skip="handleSkipPayment" />

    <Card v-else class="w-full max-w-md shadow-lg border-border/50 bg-card/50 backdrop-blur-sm hover:shadow-xl transition-all duration-500 relative z-10">
      <CardHeader class="space-y-2 text-center">
        <div class="mx-auto w-12 h-12 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center mb-2">
          <UserPlus class="w-6 h-6 text-primary-foreground" />
        </div>
        <CardTitle class="text-3xl font-bold bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent">Create Account</CardTitle>
        <CardDescription class="text-base">Sign up to get started</CardDescription>
      </CardHeader>

      <CardContent>
        <form @submit="onSubmit" class="space-y-5">
          <div class="grid grid-cols-2 gap-4">
            <div class="space-y-2">
              <Label for="firstName">First Name</Label>
              <Input id="firstName" type="text" placeholder="John" v-model="firstName" v-bind="firstNameAttrs" :disabled="isSubmitting" />
              <p v-if="errors.firstName" class="text-sm text-destructive">{{ errors.firstName }}</p>
            </div>
            <div class="space-y-2">
              <Label for="lastName">Last Name</Label>
              <Input id="lastName" type="text" placeholder="Doe" v-model="lastName" v-bind="lastNameAttrs" :disabled="isSubmitting" />
              <p v-if="errors.lastName" class="text-sm text-destructive">{{ errors.lastName }}</p>
            </div>
          </div>

          <div class="space-y-2">
            <Label for="phone">Phone Number</Label>
            <Input id="phone" type="tel" placeholder="+31636345484" v-model="phone" v-bind="phoneAttrs" :disabled="isSubmitting" />
            <p v-if="errors.phone" class="text-sm text-destructive">{{ errors.phone }}</p>
          </div>

          <div class="space-y-2">
            <Label for="email">Email</Label>
            <Input id="email" type="email" placeholder="your@email.com" v-model="email" v-bind="emailAttrs" :disabled="isSubmitting" />
            <p v-if="errors.email" class="text-sm text-destructive">{{ errors.email }}</p>
          </div>

          <div class="space-y-2">
            <Label for="password">Password</Label>
            <Input id="password" type="password" placeholder="••••••••" v-model="password" v-bind="passwordAttrs" :disabled="isSubmitting" />
            <p v-if="errors.password" class="text-sm text-destructive">{{ errors.password }}</p>
          </div>

          <Button type="submit" class="w-full bg-gradient-to-r from-primary to-accent hover:opacity-90" :disabled="isSubmitting">
            <span v-if="isSubmitting" class="flex items-center gap-2">
              <div class="w-4 h-4 border-2 border-primary-foreground/30 border-t-primary-foreground rounded-full animate-spin" />
              Creating account...
            </span>
            <span v-else>Sign Up</span>
          </Button>
        </form>

        <div class="mt-6 text-center">
          <p class="text-sm text-muted-foreground">
            Already have an account?
            <RouterLink to="/login" class="text-primary font-medium hover:underline ml-1">Sign in</RouterLink>
          </p>
        </div>
      </CardContent>
    </Card>
  </main>
</template>
