// src/views/Subscription.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { useRouter, useRoute } from "vue-router";
import { supabase } from "@/integrations/supabase/client";
import type { Session } from "@supabase/supabase-js";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import Button from "@/components/ui/button.vue";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription } from "@/components/ui/alert";
import Header from "@/components/Header.vue";
import PricingPlans from "@/components/PricingPlans.vue";
import { toast } from "vue-sonner";
import {
  CreditCard, Calendar, Clock, CheckCircle, XCircle, AlertCircle,
  ArrowLeft, Loader2, Shield, Power, PowerOff,
} from "lucide-vue-next";

interface PaymentMethod {
  id: string;
  mollie_customer_id: string | null;
  mollie_mandate_id: string | null;
  mollie_subscription_id: string | null;
  payment_method_type: string | null;
  card_last_four: string | null;
  card_expiry: string | null;
  is_active: boolean;
  trial_end_date: string | null;
  plan: string | null;
  subscription_start: string | null;
  subscription_end: string | null;
  subscription_status: string | null;
  created_at: string;
}

interface PaymentHistoryItem {
  id: string;
  mollie_payment_id: string;
  amount: string | null;
  currency: string | null;
  status: string;
  payment_type: string | null;
  description: string | null;
  paid_at: string | null;
  created_at: string;
}

const router = useRouter();
const route = useRoute();

const session = ref<Session | null>(null);
const paymentMethod = ref<PaymentMethod | null>(null);
const paymentHistory = ref<PaymentHistoryItem[]>([]);
const isLoading = ref(true);
const isToggling = ref(false);

let authSubscription: { unsubscribe: () => void } | null = null;

const fetchPaymentData = async (userId: string) => {
  const [pmRes, phRes] = await Promise.all([
    supabase.from("payment_methods").select("*").eq("user_id", userId).maybeSingle(),
    supabase.from("payment_history").select("*").eq("user_id", userId).order("created_at", { ascending: false }).limit(10),
  ]);
  if (!pmRes.error) paymentMethod.value = pmRes.data;
  if (!phRes.error) paymentHistory.value = phRes.data || [];
  isLoading.value = false;
};

const handleToggleSubscription = async () => {
  if (!session.value || !paymentMethod.value) return;
  isToggling.value = true;
  try {
    const action = paymentMethod.value.subscription_status === "active" ? "deactivate" : "activate";
    const { error } = await supabase.functions.invoke("toggle-subscription", {
      body: { userId: session.value.user.id, action },
    });
    if (error) throw error;
    paymentMethod.value = {
      ...paymentMethod.value,
      subscription_status: action === "activate" ? "active" : "inactive",
    };
    toast.success(action === "activate" ? "Subscription activated!" : "Subscription deactivated");
  } catch (err) {
    toast.error("Failed to toggle subscription");
  } finally {
    isToggling.value = false;
  }
};

onMounted(() => {
  const status = route.query.status as string;
  if (status === "paid" || status === "success") {
    toast.success("Subscription activated!", { description: "Your payment was successful." });
    router.replace({ query: {} });
  } else if (status === "failed" || status === "canceled") {
    toast.error("Payment not completed", { description: "Please try again." });
    router.replace({ query: {} });
  }

  const { data } = supabase.auth.onAuthStateChange((_event, s) => {
    session.value = s;
    if (!s) router.push("/login");
  });
  authSubscription = data.subscription;

  supabase.auth.getSession().then(({ data: { session: s } }) => {
    session.value = s;
    if (!s) {
      router.push("/login");
    } else {
      fetchPaymentData(s.user.id);
    }
  });
});

onUnmounted(() => authSubscription?.unsubscribe());

const formatDate = (dateStr: string | null) => {
  if (!dateStr) return "N/A";
  return new Date(dateStr).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" });
};
</script>

<template>
  <div class="min-h-screen bg-background">
    <Header />
    <main class="pt-4 pb-12">
      <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center gap-4 mb-8">
          <button @click="router.push('/dashboard')" class="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft class="w-5 h-5" />
            Back to Dashboard
          </button>
        </div>

        <div v-if="isLoading" class="flex items-center justify-center py-20">
          <Loader2 class="h-8 w-8 animate-spin text-primary" />
        </div>

        <div v-else class="space-y-6">
          <div v-if="!paymentMethod" class="space-y-6"
            v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0 }"
          >
            <Card>
              <CardHeader>
                <CardTitle class="flex items-center gap-2">
                  <CreditCard class="w-5 h-5" />
                  No Payment Method
                </CardTitle>
                <CardDescription>Add a payment method to access premium features</CardDescription>
              </CardHeader>
              <CardContent>
                <Alert>
                  <AlertCircle class="h-4 w-4" />
                  <AlertDescription>You haven't set up a payment method yet. Choose a plan below to get started.</AlertDescription>
                </Alert>
              </CardContent>
            </Card>

            <PricingPlans
              v-if="session"
              :user-id="session.user.id"
              :user-email="session.user.email || ''"
              :user-name="session.user.user_metadata?.full_name || ''"
            />
          </div>

          <template v-else>
            <Card v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0 }">
              <CardHeader>
                <CardTitle class="flex items-center gap-2">
                  <CreditCard class="w-5 h-5" />
                  Payment Method
                </CardTitle>
                <CardDescription>Your current payment details</CardDescription>
              </CardHeader>
              <CardContent class="space-y-4">
                <div class="flex items-center justify-between p-4 rounded-lg border bg-card">
                  <div class="flex items-center gap-3">
                    <Shield class="w-5 h-5 text-accent" />
                    <div>
                      <p class="font-medium">
                        {{ paymentMethod.payment_method_type || "Card" }}
                        <span v-if="paymentMethod.card_last_four">•••• {{ paymentMethod.card_last_four }}</span>
                      </p>
                      <p v-if="paymentMethod.card_expiry" class="text-sm text-muted-foreground">Expires {{ paymentMethod.card_expiry }}</p>
                    </div>
                  </div>
                  <Badge :variant="paymentMethod.is_active ? 'default' : 'secondary'">
                    {{ paymentMethod.is_active ? "Active" : "Inactive" }}
                  </Badge>
                </div>

                <div v-if="paymentMethod.trial_end_date" class="flex items-center gap-2 text-sm text-muted-foreground">
                  <Calendar class="w-4 h-4" />
                  Trial ends: {{ formatDate(paymentMethod.trial_end_date) }}
                </div>
              </CardContent>
            </Card>

            <Card v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0, transition: { delay: 200 } }">
              <CardHeader>
                <CardTitle class="flex items-center gap-2">
                  <component :is="paymentMethod.subscription_status === 'active' ? Power : PowerOff" class="w-5 h-5" />
                  Subscription Status
                </CardTitle>
                <CardDescription>
                  Your subscription is currently
                  <span :class="paymentMethod.subscription_status === 'active' ? 'text-accent font-medium' : 'text-muted-foreground font-medium'">
                    {{ paymentMethod.subscription_status === "active" ? "Active" : "Inactive" }}
                  </span>
                </CardDescription>
              </CardHeader>
              <CardContent class="space-y-4">
                <div class="flex items-center justify-between p-4 rounded-lg border bg-card">
                  <div class="flex items-center gap-3">
                    <div :class="['w-10 h-10 rounded-full flex items-center justify-center', paymentMethod.subscription_status === 'active' ? 'bg-accent/20' : 'bg-muted']">
                      <CheckCircle v-if="paymentMethod.subscription_status === 'active'" class="w-5 h-5 text-accent" />
                      <XCircle v-else class="w-5 h-5 text-muted-foreground" />
                    </div>
                    <div>
                      <p class="font-medium">{{ paymentMethod.subscription_status === "active" ? "Subscription Active" : "Subscription Inactive" }}</p>
                      <p class="text-sm text-muted-foreground">
                        {{ paymentMethod.subscription_status === "active" ? "You have full access to all features" : "Reactivate to regain access" }}
                      </p>
                    </div>
                  </div>
                  <Badge :class="paymentMethod.subscription_status === 'active' ? 'bg-accent/20 text-accent border-accent/30' : 'bg-muted text-muted-foreground'">
                    {{ paymentMethod.subscription_status === "active" ? "Active" : "Inactive" }}
                  </Badge>
                </div>

                <Button
                  :variant="paymentMethod.subscription_status === 'active' ? 'destructive' : 'default'"
                  @click="handleToggleSubscription"
                  :disabled="isToggling"
                  class="w-full"
                >
                  <Loader2 v-if="isToggling" class="w-4 h-4 mr-2 animate-spin" />
                  <template v-else>
                    <PowerOff v-if="paymentMethod.subscription_status === 'active'" class="w-4 h-4 mr-2" />
                    <Power v-else class="w-4 h-4 mr-2" />
                    {{ paymentMethod.subscription_status === "active" ? "Deactivate Subscription" : "Activate Subscription" }}
                  </template>
                </Button>

                <p class="text-xs text-center text-muted-foreground">
                  {{ paymentMethod.subscription_status === "active"
                    ? "Deactivating will pause your subscription. You can reactivate anytime."
                    : "Activate your subscription to regain access to all features." }}
                </p>
              </CardContent>
            </Card>

            <Card v-if="paymentHistory.length > 0" v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0, transition: { delay: 400 } }">
              <CardHeader>
                <CardTitle class="flex items-center gap-2">
                  <Clock class="w-5 h-5" />
                  Payment History
                </CardTitle>
                <CardDescription>Your recent transactions</CardDescription>
              </CardHeader>
              <CardContent>
                <div class="space-y-3">
                  <div
                    v-for="payment in paymentHistory"
                    :key="payment.id"
                    class="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50 transition-colors"
                  >
                    <div class="flex items-center gap-3">
                      <div :class="['w-10 h-10 rounded-full flex items-center justify-center', payment.status === 'paid' ? 'bg-accent/20' : 'bg-destructive/20']">
                        <CheckCircle v-if="payment.status === 'paid'" class="w-5 h-5 text-accent" />
                        <XCircle v-else class="w-5 h-5 text-destructive" />
                      </div>
                      <div>
                        <p class="font-medium text-sm">{{ payment.description || payment.payment_type || "Payment" }}</p>
                        <p class="text-xs text-muted-foreground">
                          {{ new Date(payment.created_at).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) }}
                        </p>
                      </div>
                    </div>
                    <div class="text-right">
                      <p class="font-semibold">{{ payment.currency?.toUpperCase() }} {{ payment.amount }}</p>
                      <Badge :variant="payment.status === 'paid' ? 'default' : 'destructive'" class="text-xs">{{ payment.status }}</Badge>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0, transition: { delay: 500 } }">
              <CardHeader>
                <CardTitle class="flex items-center gap-2">
                  <Calendar class="w-5 h-5" />
                  Pricing
                </CardTitle>
                <CardDescription>What you'll be charged after your trial</CardDescription>
              </CardHeader>
              <CardContent>
                <div class="space-y-4">
                  <div class="flex items-baseline justify-between">
                    <div>
                      <p class="text-3xl font-bold text-foreground">€9.99</p>
                      <p class="text-sm text-muted-foreground">per month</p>
                    </div>
                    <Badge variant="secondary">Standard Plan</Badge>
                  </div>
                  <Separator />
                  <ul class="space-y-2 text-sm">
                    <li v-for="feature in ['Unlimited voice interactions', 'Real-time navigation assistance', 'Daily news briefings', 'Family notifications', 'Priority customer support']" :key="feature" class="flex items-center gap-2">
                      <CheckCircle class="w-4 h-4 text-accent" />
                      <span>{{ feature }}</span>
                    </li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          </template>
        </div>
      </div>
    </main>
  </div>
</template>

// src/pages/Subscription.tsx
import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Session } from "@supabase/supabase-js";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { toast } from "sonner";
import { 
  CreditCard, 
  Calendar, 
  Clock, 
  CheckCircle, 
  XCircle, 
  AlertCircle,
  ArrowLeft,
  Loader2,
  Shield,
  Power,
  PowerOff
} from "lucide-react";
import Header from "@/components/Header";
import PricingPlans from "@/components/PricingPlans";
import { motion } from "framer-motion";

interface PaymentMethod {
  id: string;
  mollie_customer_id: string | null;
  mollie_mandate_id: string | null;
  mollie_subscription_id: string | null;
  payment_method_type: string | null;
  card_last_four: string | null;
  card_expiry: string | null;
  is_active: boolean;
  trial_end_date: string | null;
  plan: string | null;
  subscription_start: string | null;
  subscription_end: string | null;
  subscription_status: string | null;
  created_at: string;
}

interface PaymentHistoryItem {
  id: string;
  mollie_payment_id: string;
  amount: string | null;
  currency: string | null;
  status: string;
  payment_type: string | null;
  description: string | null;
  paid_at: string | null;
  created_at: string;
}

const Subscription = () => {
  const [session, setSession] = useState<Session | null>(null);
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod | null>(null);
  const [paymentHistory, setPaymentHistory] = useState<PaymentHistoryItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isToggling, setIsToggling] = useState(false);
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();

  // Check for Mollie redirect status
  useEffect(() => {
    const status = searchParams.get('status');
    if (status === 'paid' || status === 'success') {
      toast.success('Subscription activated!', {
        description: 'Your payment was successful and your subscription is now active.',
      });
      // Clean up URL
      searchParams.delete('status');
      setSearchParams(searchParams, { replace: true });
    } else if (status === 'failed' || status === 'canceled') {
      toast.error('Payment not completed', {
        description: 'Your payment was not completed. Please try again.',
      });
      searchParams.delete('status');
      setSearchParams(searchParams, { replace: true });
    }
  }, [searchParams, setSearchParams]);

  useEffect(() => {
    // Auth state listener
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      (event, session) => {
        setSession(session);
        if (!session) {
          navigate("/login");
        }
      }
    );

    // Check existing session
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
      if (!session) {
        navigate("/login");
      }
    });

    return () => subscription.unsubscribe();
  }, [navigate]);

  useEffect(() => {
    if (session) {
      fetchPaymentMethod();
      fetchPaymentHistory();
    }
  }, [session]);

  const fetchPaymentMethod = async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from('payment_methods')
        .select('*')
        .eq('user_id', session?.user.id)
        .maybeSingle();

      if (error) {
        console.error('Error fetching payment method:', error);
        toast.error('Failed to load subscription info');
        return;
      }

      setPaymentMethod(data);
    } catch (error) {
      console.error('Error:', error);
      toast.error('Something went wrong');
    } finally {
      setIsLoading(false);
    }
  };

  const fetchPaymentHistory = async () => {
    try {
      const { data, error } = await supabase
        .from('payment_history')
        .select('*')
        .eq('user_id', session?.user.id)
        .order('created_at', { ascending: false })
        .limit(10);

      if (error) {
        console.error('Error fetching payment history:', error);
        return;
      }

      setPaymentHistory(data || []);
    } catch (error) {
      console.error('Error:', error);
    }
  };

  const getTrialStatus = () => {
    if (!paymentMethod?.trial_end_date) {
      return { status: 'no_trial', daysLeft: 0, isActive: false };
    }

    const trialEnd = new Date(paymentMethod.trial_end_date);
    const now = new Date();
    const daysLeft = Math.ceil((trialEnd.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
    
    return {
      status: daysLeft > 0 ? 'active' : 'expired',
      daysLeft: Math.max(0, daysLeft),
      isActive: daysLeft > 0,
      endDate: trialEnd
    };
  };

  const handleToggleSubscription = async () => {
    const newStatus = paymentMethod?.subscription_status === 'active' ? 'inactive' : 'active';
    const actionText = newStatus === 'active' ? 'activate' : 'deactivate';
    
    if (!confirm(`Are you sure you want to ${actionText} your subscription?`)) {
      return;
    }

    setIsToggling(true);
    try {
      const { error } = await supabase
        .from('payment_methods')
        .update({ 
          subscription_status: newStatus,
          is_active: newStatus === 'active'
        })
        .eq('user_id', session?.user.id);

      if (error) throw error;

      toast.success(`Subscription ${newStatus === 'active' ? 'activated' : 'deactivated'}`, {
        description: newStatus === 'active' 
          ? 'Your subscription is now active.' 
          : 'Your subscription has been deactivated.',
      });

      fetchPaymentMethod();
    } catch (error) {
      console.error(`Error ${actionText}ing subscription:`, error);
      toast.error(`Failed to ${actionText} subscription`);
    } finally {
      setIsToggling(false);
    }
  };

  const handleAddPaymentMethod = async () => {
    setIsLoading(true);
    try {
      if (!session?.user) {
        toast.error('Please log in first');
        navigate('/login');
        return;
      }

      // Get user profile for name
      const { data: profile } = await supabase
        .from('profiles')
        .select('first_name, last_name')
        .eq('id', session.user.id)
        .maybeSingle();

      const name = profile 
        ? `${profile.first_name} ${profile.last_name}`.trim() 
        : session.user.email;

      toast.info('Redirecting to payment page...', {
        description: 'You will be redirected to Mollie secure checkout',
      });

      // Create Mollie customer
      const { data: customerData, error: customerError } = await supabase.functions.invoke(
        'create-mollie-customer',
        {
          body: {
            email: session.user.email,
            name: name,
          },
        }
      );

      if (customerError) {
        throw customerError;
      }

      // Create payment mandate (card verification)
      const { data: mandateData, error: mandateError } = await supabase.functions.invoke(
        'create-payment-mandate',
        {
          body: {
            customerId: customerData.customerId,
            redirectUrl: `${window.location.origin}/subscription`,
          },
        }
      );

      if (mandateError) {
        throw mandateError;
      }

      // Redirect to Mollie checkout
      if (mandateData.checkoutUrl) {
        window.location.href = mandateData.checkoutUrl;
      }
    } catch (error) {
      console.error('Payment setup error:', error);
      toast.error('Failed to setup payment', {
        description: error instanceof Error ? error.message : 'Please try again later.',
      });
      setIsLoading(false);
    }
  };

  const trialStatus = getTrialStatus();

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <>
      <Header />
      <main className="min-h-screen bg-gradient-to-br from-background via-background to-secondary/20 py-12 px-4">
        <div className="max-w-4xl mx-auto space-y-6">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <Button
              variant="ghost"
              onClick={() => navigate('/dashboard')}
              className="mb-4"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Dashboard
            </Button>
            <h1 className="text-4xl font-bold text-foreground mb-2">Subscription Management</h1>
            <p className="text-muted-foreground">Manage your subscription and payment settings</p>
          </motion.div>

          {/* Trial Status Card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Clock className="w-5 h-5" />
                  Trial Status
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {!paymentMethod ? (
                  <Alert>
                    <AlertCircle className="h-4 w-4" />
                    <AlertDescription>
                      No payment method on file. Add a payment method to start your free trial.
                    </AlertDescription>
                  </Alert>
                ) : trialStatus.isActive ? (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm text-muted-foreground">Trial Period</p>
                        <p className="text-2xl font-bold text-foreground">
                          {trialStatus.daysLeft} {trialStatus.daysLeft === 1 ? 'day' : 'days'} remaining
                        </p>
                      </div>
                      <Badge className="bg-accent/20 text-accent border-accent/30">
                        <CheckCircle className="w-3 h-3 mr-1" />
                        Active Trial
                      </Badge>
                    </div>
                    <Separator />
                    <div className="grid grid-cols-2 gap-4 text-sm">
                      <div>
                        <p className="text-muted-foreground">Trial Started</p>
                        <p className="font-medium">
                          {new Date(paymentMethod.created_at).toLocaleDateString()}
                        </p>
                      </div>
                      <div>
                        <p className="text-muted-foreground">Trial Ends</p>
                        <p className="font-medium">
                          {trialStatus.endDate?.toLocaleDateString()}
                        </p>
                      </div>
                    </div>
                    {trialStatus.daysLeft <= 3 && (
                      <Alert className="border-amber-500/50 bg-amber-500/10">
                        <AlertCircle className="h-4 w-4 text-amber-500" />
                        <AlertDescription className="text-amber-700 dark:text-amber-300">
                          Your trial is ending soon. Your card will be charged automatically unless you cancel.
                        </AlertDescription>
                      </Alert>
                    )}
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm text-muted-foreground">Trial Status</p>
                        <p className="text-2xl font-bold text-foreground">Expired</p>
                      </div>
                      <Badge variant="destructive">
                        <XCircle className="w-3 h-3 mr-1" />
                        Trial Ended
                      </Badge>
                    </div>
                    <Alert variant="destructive">
                      <AlertCircle className="h-4 w-4" />
                      <AlertDescription>
                        Your trial has ended. Subscribe now to continue using premium features.
                      </AlertDescription>
                    </Alert>
                  </div>
                )}
              </CardContent>
            </Card>
          </motion.div>

          {/* Plan Selection - Always show pricing options */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.15 }}
          >
            <Card>
              <CardHeader>
                <CardTitle>Choose Your Plan</CardTitle>
                <CardDescription>
                  {paymentMethod ? "Upgrade or change your subscription plan" : "Select a plan to start your 7-day free trial"}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <PricingPlans
                  userId={session?.user.id || ""}
                  userEmail={session?.user.email || ""}
                  userName={session?.user.user_metadata?.first_name 
                    ? `${session.user.user_metadata.first_name} ${session.user.user_metadata.last_name || ""}`.trim()
                    : session?.user.email || ""}
                  currentPlan={paymentMethod?.plan}
                  currentDuration={null}
                  isUpgrade={!!paymentMethod}
                  onSubscriptionCreated={() => {
                    fetchPaymentMethod();
                    fetchPaymentHistory();
                  }}
                />
              </CardContent>
            </Card>
          </motion.div>

          {/* Payment Method Card */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <CreditCard className="w-5 h-5" />
                  Payment Method
                </CardTitle>
                <CardDescription>Manage your payment information</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {paymentMethod ? (
                  <div className="space-y-4">
                    <div className="flex items-center justify-between p-4 border rounded-lg bg-card">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
                          <CreditCard className="w-6 h-6 text-primary" />
                        </div>
                        <div>
                          <p className="font-medium">
                            {paymentMethod.card_last_four 
                              ? `•••• ${paymentMethod.card_last_four}`
                              : 'No card verified yet'}
                          </p>
                          <p className="text-sm text-muted-foreground">
                            {paymentMethod.card_last_four 
                              ? `${paymentMethod.payment_method_type || 'Credit Card'}${paymentMethod.card_expiry ? ` • Expires ${paymentMethod.card_expiry}` : ''}`
                              : 'Complete card verification to activate'}
                          </p>
                          {paymentMethod.plan && (
                            <p className="text-sm font-medium text-primary mt-1">
                              Plan: {paymentMethod.plan}
                            </p>
                          )}
                        </div>
                      </div>
                      {paymentMethod.card_last_four && paymentMethod.mollie_mandate_id ? (
                        paymentMethod.is_active ? (
                          <Badge className="bg-accent/20 text-accent border-accent/30">
                            <CheckCircle className="w-3 h-3 mr-1" />
                            Active
                          </Badge>
                        ) : (
                          <Badge variant="secondary">
                            Inactive
                          </Badge>
                        )
                      ) : (
                        <Badge variant="outline" className="border-amber-500/50 text-amber-600">
                          <AlertCircle className="w-3 h-3 mr-1" />
                          Pending
                        </Badge>
                      )}
                    </div>
                    
                    {paymentMethod.mollie_subscription_id && (
                      <div className="p-4 border rounded-lg bg-background/50 space-y-3">
                        <h4 className="font-medium text-sm flex items-center gap-2">
                          <Calendar className="w-4 h-4" />
                          Subscription Details
                        </h4>
                        <div className="grid grid-cols-2 gap-3 text-sm">
                          <div>
                            <span className="text-muted-foreground">Status:</span>
                            <span className={`ml-2 font-medium ${
                              paymentMethod.subscription_status === 'active' 
                                ? 'text-accent' 
                                : 'text-muted-foreground'
                            }`}>
                              {paymentMethod.subscription_status || 'inactive'}
                            </span>
                          </div>
                          {paymentMethod.subscription_start && (
                            <div>
                              <span className="text-muted-foreground">Started:</span>
                              <span className="ml-2 font-medium">
                                {new Date(paymentMethod.subscription_start).toLocaleDateString()}
                              </span>
                            </div>
                          )}
                          {paymentMethod.subscription_end && (
                            <div className="col-span-2">
                              <span className="text-muted-foreground">Ends:</span>
                              <span className="ml-2 font-medium">
                                {new Date(paymentMethod.subscription_end).toLocaleDateString()}
                              </span>
                            </div>
                          )}
                        </div>
                      </div>
                    )}
                    
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Shield className="w-4 h-4" />
                      <span>Secured by Mollie payment processing</span>
                    </div>
                  </div>
                ) : null}
              </CardContent>
            </Card>
          </motion.div>

          {/* Subscription Actions */}
          {paymentMethod && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
            >
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    {paymentMethod.subscription_status === 'active' ? (
                      <Power className="w-5 h-5 text-accent" />
                    ) : (
                      <PowerOff className="w-5 h-5 text-muted-foreground" />
                    )}
                    Subscription Status
                  </CardTitle>
                  <CardDescription>
                    Your subscription is currently{' '}
                    <span className={paymentMethod.subscription_status === 'active' ? 'text-accent font-medium' : 'text-muted-foreground font-medium'}>
                      {paymentMethod.subscription_status === 'active' ? 'Active' : 'Inactive'}
                    </span>
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-center justify-between p-4 rounded-lg border bg-card">
                    <div className="flex items-center gap-3">
                      {paymentMethod.subscription_status === 'active' ? (
                        <div className="w-10 h-10 rounded-full bg-accent/20 flex items-center justify-center">
                          <CheckCircle className="w-5 h-5 text-accent" />
                        </div>
                      ) : (
                        <div className="w-10 h-10 rounded-full bg-muted flex items-center justify-center">
                          <XCircle className="w-5 h-5 text-muted-foreground" />
                        </div>
                      )}
                      <div>
                        <p className="font-medium">
                          {paymentMethod.subscription_status === 'active' ? 'Subscription Active' : 'Subscription Inactive'}
                        </p>
                        <p className="text-sm text-muted-foreground">
                          {paymentMethod.subscription_status === 'active' 
                            ? 'You have full access to all features'
                            : 'Reactivate to regain access to features'}
                        </p>
                      </div>
                    </div>
                    <Badge className={paymentMethod.subscription_status === 'active' 
                      ? 'bg-accent/20 text-accent border-accent/30' 
                      : 'bg-muted text-muted-foreground'}>
                      {paymentMethod.subscription_status === 'active' ? 'Active' : 'Inactive'}
                    </Badge>
                  </div>
                  
                  <Button
                    variant={paymentMethod.subscription_status === 'active' ? 'destructive' : 'default'}
                    onClick={handleToggleSubscription}
                    disabled={isToggling}
                    className="w-full"
                  >
                    {isToggling ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        {paymentMethod.subscription_status === 'active' ? 'Deactivating...' : 'Activating...'}
                      </>
                    ) : paymentMethod.subscription_status === 'active' ? (
                      <>
                        <PowerOff className="w-4 h-4 mr-2" />
                        Deactivate Subscription
                      </>
                    ) : (
                      <>
                        <Power className="w-4 h-4 mr-2" />
                        Activate Subscription
                      </>
                    )}
                  </Button>
                  <p className="text-xs text-center text-muted-foreground">
                    {paymentMethod.subscription_status === 'active' 
                      ? 'Deactivating will pause your subscription. You can reactivate anytime.'
                      : 'Activate your subscription to regain access to all features.'}
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Payment History */}
          {paymentHistory.length > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.4 }}
            >
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Clock className="w-5 h-5" />
                    Payment History
                  </CardTitle>
                  <CardDescription>Your recent transactions</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {paymentHistory.map((payment) => (
                      <div
                        key={payment.id}
                        className="flex items-center justify-between p-3 border rounded-lg hover:bg-muted/50 transition-colors"
                      >
                        <div className="flex items-center gap-3">
                          <div className={`w-10 h-10 rounded-full flex items-center justify-center ${
                            payment.status === 'paid' 
                              ? 'bg-accent/20' 
                              : 'bg-destructive/20'
                          }`}>
                            {payment.status === 'paid' ? (
                              <CheckCircle className="w-5 h-5 text-accent" />
                            ) : (
                              <XCircle className="w-5 h-5 text-destructive" />
                            )}
                          </div>
                          <div>
                            <p className="font-medium text-sm">
                              {payment.description || payment.payment_type || 'Payment'}
                            </p>
                            <p className="text-xs text-muted-foreground">
                              {new Date(payment.created_at).toLocaleDateString('en-US', {
                                year: 'numeric',
                                month: 'short',
                                day: 'numeric',
                                hour: '2-digit',
                                minute: '2-digit'
                              })}
                            </p>
                          </div>
                        </div>
                        <div className="text-right">
                          <p className="font-semibold">
                            {payment.currency?.toUpperCase()} {payment.amount}
                          </p>
                          <Badge 
                            variant={payment.status === 'paid' ? 'default' : 'destructive'}
                            className="text-xs"
                          >
                            {payment.status}
                          </Badge>
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Pricing Information */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.5 }}
          >
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Calendar className="w-5 h-5" />
                  Pricing
                </CardTitle>
                <CardDescription>What you'll be charged after your trial</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-baseline justify-between">
                    <div>
                      <p className="text-3xl font-bold text-foreground">€9.99</p>
                      <p className="text-sm text-muted-foreground">per month</p>
                    </div>
                    <Badge variant="secondary">Standard Plan</Badge>
                  </div>
                  <Separator />
                  <ul className="space-y-2 text-sm">
                    <li className="flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-accent" />
                      <span>Unlimited voice interactions</span>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-accent" />
                      <span>Real-time navigation assistance</span>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-accent" />
                      <span>Daily news briefings</span>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-accent" />
                      <span>Family notifications</span>
                    </li>
                    <li className="flex items-center gap-2">
                      <CheckCircle className="w-4 h-4 text-accent" />
                      <span>Priority customer support</span>
                    </li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </main>
    </>
  );
};

export default Subscription;
